export const types = Object.freeze({
    // Sync
    SERVICES_START_FETCHING: 'SERVICES_START_FETCHING',
    SERVICES_STOP_FETCHING: 'SERVICES_STOP_FETCHING',
    SERVICES_FILL: 'SERVICES_FILL',
    SERVICES_SET_FETCHING_ERROR: 'SERVICES_SET_FETCHING_ERROR',
    // Async
    SERVICES_FETCH_ASYNC: 'SERVICES_FETCH_ASYNC',
});
